-- MySQL Script generated by MySQL Workbench
-- sáb 05 may 2018 21:55:46 -03
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema todoHogar
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema todoHogar
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `todoHogar` DEFAULT CHARACTER SET utf8 ;
USE `todoHogar` ;

-- -----------------------------------------------------
-- Table `todoHogar`.`provincia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `todoHogar`.`provincia` (
  `idprovincia` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idprovincia`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `todoHogar`.`localidad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `todoHogar`.`localidad` (
  `idlocalidad` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(80) NOT NULL,
  `codigoPostal` INT NULL,
  `provincia_idprovincia` INT NOT NULL,
  PRIMARY KEY (`idlocalidad`),
  INDEX `fk_localidad_provincia1_idx` (`provincia_idprovincia` ASC),
  CONSTRAINT `fk_localidad_provincia1`
    FOREIGN KEY (`provincia_idprovincia`)
    REFERENCES `todoHogar`.`provincia` (`idprovincia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `todoHogar`.`domicilio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `todoHogar`.`domicilio` (
  `iddomicilio` INT NOT NULL AUTO_INCREMENT,
  `calle` VARCHAR(45) NOT NULL,
  `numero` VARCHAR(45) NOT NULL,
  `piso` VARCHAR(10) NULL,
  `departamento` VARCHAR(10) NULL,
  `localidad_idlocalidad` INT NOT NULL,
  PRIMARY KEY (`iddomicilio`),
  INDEX `fk_domicilio_localidad1_idx` (`localidad_idlocalidad` ASC),
  CONSTRAINT `fk_domicilio_localidad1`
    FOREIGN KEY (`localidad_idlocalidad`)
    REFERENCES `todoHogar`.`localidad` (`idlocalidad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `todoHogar`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `todoHogar`.`cliente` (
  `idcliente` INT NOT NULL AUTO_INCREMENT,
  `apellido` VARCHAR(45) NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `telefono` INT NULL,
  `domicilio_iddomicilio` INT NOT NULL,
  PRIMARY KEY (`idcliente`),
  INDEX `fk_cliente_domicilio1_idx` (`domicilio_iddomicilio` ASC),
  CONSTRAINT `fk_cliente_domicilio1`
    FOREIGN KEY (`domicilio_iddomicilio`)
    REFERENCES `todoHogar`.`domicilio` (`iddomicilio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `todoHogar`.`perfil`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `todoHogar`.`perfil` (
  `idperfil` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idperfil`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `todoHogar`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `todoHogar`.`usuario` (
  `idusuario` INT NOT NULL AUTO_INCREMENT,
  `nombreUsuario` VARCHAR(45) NOT NULL,
  `clave` VARCHAR(45) NOT NULL,
  `perfil_idperfil` INT NOT NULL,
  PRIMARY KEY (`idusuario`),
  INDEX `fk_usuario_perfil1_idx` (`perfil_idperfil` ASC),
  CONSTRAINT `fk_usuario_perfil1`
    FOREIGN KEY (`perfil_idperfil`)
    REFERENCES `todoHogar`.`perfil` (`idperfil`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `todoHogar`.`cargo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `todoHogar`.`cargo` (
  `idcargo` INT NOT NULL AUTO_INCREMENT,
  `cargo` VARCHAR(45) NOT NULL,
  `basico` FLOAT NOT NULL,
  PRIMARY KEY (`idcargo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `todoHogar`.`empleado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `todoHogar`.`empleado` (
  `idempleado` INT NOT NULL AUTO_INCREMENT,
  `apellido` VARCHAR(45) NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `dni` INT NOT NULL,
  `telefono` INT NULL,
  `fechaIngreso` DATE NOT NULL,
  `sexo` CHAR(1) NOT NULL,
  `estado` VARCHAR(10) NOT NULL,
  `domicilio_iddomicilio` INT NOT NULL,
  `usuario_idusuario` INT NOT NULL,
  `cargo_idcargo` INT NOT NULL,
  PRIMARY KEY (`idempleado`),
  INDEX `fk_empleado_usuario1_idx` (`usuario_idusuario` ASC),
  INDEX `fk_empleado_domicilio1_idx` (`domicilio_iddomicilio` ASC),
  INDEX `fk_empleado_cargo1_idx` (`cargo_idcargo` ASC),
  CONSTRAINT `fk_empleado_usuario1`
    FOREIGN KEY (`usuario_idusuario`)
    REFERENCES `todoHogar`.`usuario` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_empleado_domicilio1`
    FOREIGN KEY (`domicilio_iddomicilio`)
    REFERENCES `todoHogar`.`domicilio` (`iddomicilio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_empleado_cargo1`
    FOREIGN KEY (`cargo_idcargo`)
    REFERENCES `todoHogar`.`cargo` (`idcargo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `todoHogar`.`venta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `todoHogar`.`venta` (
  `idventa` INT NOT NULL AUTO_INCREMENT,
  `fecha` DATE NOT NULL,
  `total` FLOAT NOT NULL,
  `cliente_idcliente` INT NOT NULL,
  `empleado_idempleado` INT NOT NULL,
  PRIMARY KEY (`idventa`),
  INDEX `fk_venta_cliente_idx` (`cliente_idcliente` ASC),
  INDEX `fk_venta_empleado1_idx` (`empleado_idempleado` ASC),
  CONSTRAINT `fk_venta_cliente`
    FOREIGN KEY (`cliente_idcliente`)
    REFERENCES `todoHogar`.`cliente` (`idcliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_venta_empleado1`
    FOREIGN KEY (`empleado_idempleado`)
    REFERENCES `todoHogar`.`empleado` (`idempleado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `todoHogar`.`categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `todoHogar`.`categoria` (
  `idcategoria` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idcategoria`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `todoHogar`.`producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `todoHogar`.`producto` (
  `idproducto` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(45) NOT NULL,
  `stock` INT NOT NULL,
  `precioCompra` DOUBLE NOT NULL,
  `precioVenta` DOUBLE NOT NULL,
  `categoria_idcategoria` INT NOT NULL,
  PRIMARY KEY (`idproducto`),
  INDEX `fk_producto_categoria1_idx` (`categoria_idcategoria` ASC),
  CONSTRAINT `fk_producto_categoria1`
    FOREIGN KEY (`categoria_idcategoria`)
    REFERENCES `todoHogar`.`categoria` (`idcategoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `todoHogar`.`linea_venta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `todoHogar`.`linea_venta` (
  `idlineaVenta` INT NOT NULL AUTO_INCREMENT,
  `cantidad` INT NOT NULL,
  `precio` DOUBLE NOT NULL,
  `venta_idventa` INT NOT NULL,
  `producto_idproducto` INT NOT NULL,
  PRIMARY KEY (`idlineaVenta`),
  INDEX `fk_lineaVenta_venta1_idx` (`venta_idventa` ASC),
  INDEX `fk_linea_venta_producto1_idx` (`producto_idproducto` ASC),
  CONSTRAINT `fk_lineaVenta_venta1`
    FOREIGN KEY (`venta_idventa`)
    REFERENCES `todoHogar`.`venta` (`idventa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_linea_venta_producto1`
    FOREIGN KEY (`producto_idproducto`)
    REFERENCES `todoHogar`.`producto` (`idproducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `todoHogar`.`proveedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `todoHogar`.`proveedor` (
  `idproveedor` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `razonSocial` VARCHAR(45) NOT NULL,
  `cuit` BIGINT(11) NOT NULL,
  `telefono` INT NOT NULL,
  `correo` VARCHAR(60) NULL,
  `domicilio_iddomicilio` INT NOT NULL,
  PRIMARY KEY (`idproveedor`),
  INDEX `fk_proveedor_domicilio1_idx` (`domicilio_iddomicilio` ASC),
  CONSTRAINT `fk_proveedor_domicilio1`
    FOREIGN KEY (`domicilio_iddomicilio`)
    REFERENCES `todoHogar`.`domicilio` (`iddomicilio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `todoHogar`.`compra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `todoHogar`.`compra` (
  `idcompra` INT NOT NULL AUTO_INCREMENT,
  `fecha` DATE NOT NULL,
  `total` FLOAT NOT NULL,
  `empleado_idempleado` INT NOT NULL,
  `proveedor_idproveedor` INT NOT NULL,
  PRIMARY KEY (`idcompra`),
  INDEX `fk_pedido_empleado1_idx` (`empleado_idempleado` ASC),
  INDEX `fk_pedido_proveedor1_idx` (`proveedor_idproveedor` ASC),
  CONSTRAINT `fk_pedido_empleado1`
    FOREIGN KEY (`empleado_idempleado`)
    REFERENCES `todoHogar`.`empleado` (`idempleado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pedido_proveedor1`
    FOREIGN KEY (`proveedor_idproveedor`)
    REFERENCES `todoHogar`.`proveedor` (`idproveedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `todoHogar`.`linea_compra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `todoHogar`.`linea_compra` (
  `idlineacompra` INT NOT NULL AUTO_INCREMENT,
  `cantidad` INT NOT NULL,
  `precio` DOUBLE NOT NULL,
  `producto_idproducto` INT NOT NULL,
  `compra_idcompra` INT NOT NULL,
  PRIMARY KEY (`idlineacompra`),
  INDEX `fk_linea_pedido_producto1_idx` (`producto_idproducto` ASC),
  INDEX `fk_linea_compra_compra1_idx` (`compra_idcompra` ASC),
  CONSTRAINT `fk_linea_pedido_producto1`
    FOREIGN KEY (`producto_idproducto`)
    REFERENCES `todoHogar`.`producto` (`idproducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_linea_compra_compra1`
    FOREIGN KEY (`compra_idcompra`)
    REFERENCES `todoHogar`.`compra` (`idcompra`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `todoHogar`.`liquidacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `todoHogar`.`liquidacion` (
  `idliquidacion` INT NOT NULL AUTO_INCREMENT,
  `año` INT NOT NULL,
  `mes` INT NOT NULL,
  `sueldoNeto` DOUBLE NOT NULL,
  `totalHaberes` DOUBLE NOT NULL,
  `totalDescuentos` DOUBLE NOT NULL,
  `empleado_idempleado` INT NOT NULL,
  PRIMARY KEY (`idliquidacion`),
  INDEX `fk_liquidacion_empleado1_idx` (`empleado_idempleado` ASC),
  CONSTRAINT `fk_liquidacion_empleado1`
    FOREIGN KEY (`empleado_idempleado`)
    REFERENCES `todoHogar`.`empleado` (`idempleado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `todoHogar`.`concepto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `todoHogar`.`concepto` (
  `idconcepto` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(120) NOT NULL,
  `tipoConcepto` VARCHAR(45) NOT NULL,
  `fijo` VARCHAR(10) NOT NULL,
  `porcentaje` DOUBLE NULL,
  `monto` DOUBLE NULL,
  PRIMARY KEY (`idconcepto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `todoHogar`.`linea_liquidacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `todoHogar`.`linea_liquidacion` (
  `idlinea_liquidacion` INT NOT NULL AUTO_INCREMENT,
  `monto` DOUBLE NOT NULL,
  `cantidad` INT NOT NULL,
  `liquidacion_idliquidacion` INT NOT NULL,
  `concepto_idconcepto` INT NOT NULL,
  PRIMARY KEY (`idlinea_liquidacion`),
  INDEX `fk_linea_liquidacion_liquidacion1_idx` (`liquidacion_idliquidacion` ASC),
  INDEX `fk_linea_liquidacion_concepto1_idx` (`concepto_idconcepto` ASC),
  CONSTRAINT `fk_linea_liquidacion_liquidacion1`
    FOREIGN KEY (`liquidacion_idliquidacion`)
    REFERENCES `todoHogar`.`liquidacion` (`idliquidacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_linea_liquidacion_concepto1`
    FOREIGN KEY (`concepto_idconcepto`)
    REFERENCES `todoHogar`.`concepto` (`idconcepto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `todoHogar`.`familia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `todoHogar`.`familia` (
  `idfamilia` INT NOT NULL AUTO_INCREMENT,
  `dni` INT NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `vinculo` VARCHAR(45) NOT NULL,
  `fechaNacimiento` DATE NOT NULL,
  `discapacidad` VARCHAR(45) NOT NULL,
  `escolaridad` VARCHAR(45) NOT NULL,
  `empleado_idempleado` INT NOT NULL,
  PRIMARY KEY (`idfamilia`),
  INDEX `fk_familia_empleado1_idx` (`empleado_idempleado` ASC),
  CONSTRAINT `fk_familia_empleado1`
    FOREIGN KEY (`empleado_idempleado`)
    REFERENCES `todoHogar`.`empleado` (`idempleado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
